permalink: pretty

title: Elliot Outland
description: The homepage of Elliot Outland.
url: https://www.ehoutland.com

logo: TBD
twitter_username: ehoutland
github_username: ehoutland

theme: jekyll-theme-minimal
